on:
  push:
    tags:
      - '*'

name: CI

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          TARGET: aarch64-apple-darwin
        - os: ubuntu-latest
          TARGET: aarch64-unknown-linux-gnu
        - os: ubuntu-latest
          TARGET: armv7-unknown-linux-gnueabihf
        - os: ubuntu-latest
          TARGET: x86_64-unknown-linux-gnu
        - os: windows-latest
          TARGET: x86_64-pc-windows-msvc
          EXTENSION: .exe

    steps:
    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"

    - uses: actions/checkout@master

    - name: Install build dependencies - Rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile default --target ${{ matrix.TARGET }} -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install ALSA development libraries (Ubuntu only)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install pkg-config
        sudo apt-get install libasound2-dev
        sudo apt-get install libjack-jackd2-dev libjack-jackd2-0
        pkg-config --modversion alsa
  
    - name: Install cross for linux
      if: contains(matrix.TARGET, 'linux')
      run: |
        cargo install cross --git https://github.com/cross-rs/cross --rev 1b8cf50d20180c1a394099e608141480f934b7f7
        
    - name: Install cross for mac and windows
      if: ${{ !contains(matrix.TARGET, 'linux') }}
      run: |
        cargo install cross

    - name: Build
      working-directory: ./rpgm-viewer
      run: |
        export CROSS_DEB_PACKAGES=libasound2-dev
        export PKG_CONFIG_PATH=/usr/lib/${{ matrix.TARGET }}/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
        cross run --target ${{ matrix.TARGET }} -- sh -c 'ls -l /usr/lib/${{ matrix.TARGET }}/pkgconfig/ || echo "Directory not found"'
        cross run --target ${{ matrix.TARGET }} -- sh -c 'pkg-config --modversion alsa || echo "pkg-config failed"'
        echo "PKG_CONFIG_PATH is set to: $PKG_CONFIG_PATH"
        cross build --verbose --release --target=${{ matrix.TARGET }}

    - name: Rename
      run: cp ./rpgm-viewer/target/${{ matrix.TARGET }}/release/rpg_viewer${{ matrix.EXTENSION }} rpg_viewer-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

    - uses: actions/upload-artifact@master
      with:
        name: rpg_viewer-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
        path: rpg_viewer-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

    - uses: svenstaro/upload-release-action@v2
      name: Upload binaries to release
      if: ${{ github.event_name == 'push' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: rpg_viewer-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
        asset_name: rpg_viewer-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
        tag: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        overwrite: true